### ISSUE TITLE
First simple reading automate. 

### ISSUE THREAD

**Issue by ghost** [alxarsenault/Words#2]

**Comment by p-groarke** [comment]
Yesser, ca senviens. Jcommence par faire les chaines de markov (la longueur) et apres je vais implementer stdin.

**Comment by p-groarke** [comment]
Pas mal donne. Reste p-e du nettoyage (addword(); word = "."; addWord()) et rajouter des chars. Pour l'instant ca fonctionne assez bien. J'embarque sur le bruteforce de phrases!
